name: Deploy to Production
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 167.172.160.46
          username: internet_magazin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/internet_magazin
            git pull
            npm install
            npm run build
            pm2 restart all
